[global]
developmentMode = false

[server]
port = 8080
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false

[browser]
gatherUsageStats = false
serverAddress = "iq293zctgb.eu-central-1.awsapprunner.com"
serverPort = 443